version: '3'

services:
    laravel-app:
      build: .
      ports:
        - "8000:80"
      volumes:
        - ./:/usr/share/nginx
      networks:
        - app-network

    mysql-app:
      image: mysql:8.0
      #command: --innodb-use-native-aio=0 ### Para windows
      restart: always
      ports:
        - "3306:3306"
      volumes:
        - /var/lib/dbdata:/var/lib/mysql
      environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: laravel
      networks:
        - app-network

networks:
  app-network:
    driver: bridge